CREATE TABLE `volunteers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `date_applied` DATE NOT NULL,
  `street_address` VARCHAR(200),
  `city` VARCHAR(60),
  `province` ENUM('Ontario', 'Just Visiting'),
  `postal_code` VARCHAR(7),
  `contact_phone` VARCHAR(15),
  `email_address` VARCHAR(100),
  `tuesday_9am_12pm` TINYINT(1) DEFAULT 0,
  `tuesday_1pm_4pm` TINYINT(1) DEFAULT 0,
  `wednesday_9am_12pm` TINYINT(1) DEFAULT 0,
  `wednesday_1pm_4pm` TINYINT(1) DEFAULT 0,
  `thursday_9am_12pm` TINYINT(1) DEFAULT 0,
  `thursday_1pm_4pm` TINYINT(1) DEFAULT 0,
  `monday_9am_12pm` TINYINT(1) DEFAULT 0,
  `monday_1pm_4pm` TINYINT(1) DEFAULT 0,
  `saturday_9am_12pm` TINYINT(1) DEFAULT 0,
  `saturday_1pm_4pm` TINYINT(1) DEFAULT 0,
  `physical_considerations` ENUM('Yes', 'No'),
  `physical_explanation` TEXT,
  `emergency_contact_name` VARCHAR(60),
  `emergency_relationship` VARCHAR(60),
  `emergency_phone` VARCHAR(15),
  `hobbies_skills_interests` TEXT,
  `special_training_certification` TEXT,
  `prompted_by` TEXT,
  `languages_spoken` TEXT
);
